-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 00:05:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_adress
-- -----------------------------------------------------
-- utf8-unicode
--
DROP SCHEMA IF EXISTS `database_adress` ;

-- -----------------------------------------------------
-- Schema database_adress
--
-- utf8-unicode
--
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_adress` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `database_adress` ;

-- -----------------------------------------------------
-- Table `database_adress`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_adress`.`region` ;

CREATE TABLE IF NOT EXISTS `database_adress`.`region` (
  `id_region` INT NOT NULL AUTO_INCREMENT,
  `nombre_region` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id_region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_adress`.`comuna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_adress`.`comuna` ;

CREATE TABLE IF NOT EXISTS `database_adress`.`comuna` (
  `id_comuna` INT NOT NULL AUTO_INCREMENT,
  `nombre_comuna` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `id_region_fk` INT NOT NULL,
  PRIMARY KEY (`id_comuna`),
  INDEX `fk_comuna_region1_idx` (`id_region_fk` ASC),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`id_region_fk`)
    REFERENCES `database_adress`.`region` (`id_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_adress`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_adress`.`direccion` ;

CREATE TABLE IF NOT EXISTS `database_adress`.`direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `nombre_calle` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `numero` INT(8) NOT NULL,
  `depto` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `id_comuna_fk` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_direccion_comuna1_idx` (`id_comuna_fk` ASC),
  CONSTRAINT `fk_direccion_comuna1`
    FOREIGN KEY (`id_comuna_fk`)
    REFERENCES `database_adress`.`comuna` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;